version: 2.1
executors:
  node18:
    docker:
      - image: cimg/node:18.17

orbs:
  helix-post-deploy: adobe/helix-post-deploy@3.0.1
  helix-gcloud-setup: adobe/helix-gcloud-setup@1.0.1
  codecov: codecov/codecov@3.2.5

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node18
    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Running tests and getting code coverage
          command: npm run test
      - codecov/upload
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

  semantic-release:
    executor: node18
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - helix-post-deploy/config-env
      - run:
          name: Semantic Release
          command: npm run semantic-release
      - run:
          name: Post-Deployment Integration Test
          command: npm run test-postdeploy
      - store_test_results:
          path: junit
      - run:
          name: Link Sequences
          command: npm run deploy-routes
      - helix-post-deploy/monitoring:
          targets: universal, aws
  branch-deploy:
    executor: node18
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - run:
          name: Branch Deployment
          command: npm run deploy-ci
      - run:
          name: Post-Deployment Integration Test
          command: npm run test-postdeploy
      - store_test_results:
          path: junit

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Project Helix
      - branch-deploy:
          context: Project Helix
          requires:
            - build
          filters:
            branches:
              ignore: main
      - semantic-release:
          context: Project Helix
          requires:
            - build
          filters:
            branches:
              only: main

# VS Code Extension Version: 1.5.1
